config/routes.rb
Rails.application.routes.draw do
 root 'top#main'
 get 'top/main'
 resources :products
 resources :cart_items, only:[:create,:destroy]
 resources :carts,only:[:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
     def current_cart
      if session[:cart_id]
        cart = Cart.find(session[:cart_id])
      else
        cart = Cart.create
        session[:cart_id] = cart.id
      end
     cart
     end
     helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
     def create
      @product = Product.new()
      @product.save
      redirect_to '/'
     end
      def destroy
       @product = Product.find(params[:cart_id])
       @product.destroy
       redirect_to '/'
      end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
    @product = Product.find(params[:cart_id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      @products = Product.all
    end
    def new
      @product = Product.new
    end
     def create
      @product = Product.new()
      @product.save
      redirect_to '/'
     end
      def destroy
       @product = Product.find(params[:products_id])
       @product.destroy
       redirect_to '/'
      end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        @product = Product.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/main.html.erb
<% if flash[:info] %>
<%= flash[:info] %>
<% end %>

<% @products.each do |e| %>
<p>
  <%= e.uid %>
  <%= e.pass %>
  <%= link_to '削除', user_path(e), method: :delete %>
</p>
<% end %>

<p><%= link_to '商品カート', new_products_path %></p>

<p><%= link_to '戻る', :back %></p>